version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0
        auth:
          username: lexarflash8g
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
          docker_layer_caching:
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t lexarflash8g/python-flask-aws:$TAG .
          echo "$DOCKER_PASS" | docker login --username lexarflash8g --password-stdin
          docker push lexarflash8g/python-flask-aws:$TAG
  test:
    docker:
      - image: circleci/python:3.8.0
        auth:
          username: lexarflash8g
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "this is a test"
workflows:
    build_and_test:
      jobs:
        - build
        - test:
            requires:
              - build

