version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0
        auth:
          username: lexarflash8g
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
          docker_layer_caching:
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t lexarflash8g/python-flask-aws:$TAG .
          echo "$DOCKER_PASS" | docker login --username lexarflash8g --password-stdin
          docker push lexarflash8g/python-flask-aws:$TAG
  test:
    docker:
      - image: circleci/python:3.8.0
        auth:
          username: lexarflash8g
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "this is a test"

  build-infrastructure:
    docker:
    - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum -y install gzip tar
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
            --template-file kubernetes.yaml \
            --tags project=python-flask-aws \
            --stack-name "kubernetes-${CIRCLE_WORKFLOW_ID}" \
            --parameter-overrides EKSClusterName=eksclusterprod, EKSIAMRoleName=eksrole-iam \
            --capabilities CAPABILITY_NAMED_IAM

      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
            --template-file kubernetes.yaml \
            --tags project=python-flask-aws \
            --stack-name "kubernetes-${CIRCLE_WORKFLOW_ID}" \
            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}" \
            --capabilities CAPABILITY_NAMED_IAM
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install aws-iam-authenticator
          command: |
            curl -o aws-iam-authenticator curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
      - run: 
          name: Install kubectl
          command: |
            curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
    
workflows:
    build_and_test:
      jobs:
        - deploy-infrastructure
        - build-infrastructure
            
