apiVersion: v1
kind: Service
metadata:
  name: python-flask-aws
spec:
  selector:
    app: python-flask
  ports:
  - protocol: "TCP"
    port: 81
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask
spec:
  selector:
    matchLabels:
      app: python-flask
  replicas: 2
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
        - name: python-flask
          image: lexarflash8g/python-flask-aws:0.1.69
          ports:
            - containerPort: 80