apiVersion: apps/v1
kind: Deployment
metadata: 
  name: python-flask
  namespace: default
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
        - image: lexarflash8g/python-flask-aws:$TAG
          imagePullPolicy: Always
          name: python-flask
          ports:
            - containerPort: 80
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /
              port: 80
              