apiVersion: apps/v1
kind: Deployment
metadata: 
  name: python-flask-aws
  namespace: default
spec: 
  replicas: 2
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
        - image: lexarflash8g/python-flask-aws:$TAG
          imagePullPolicy: Always
          name: hello-dep
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
              initialDelaySecond: 5
              periodSecond: 5
              successThreshold: 1